### ISSUE TITLE
Sublime Text symlink in setup broken on Mac

### ISSUE THREAD

**Issue by anonrab** [HaxeFlixel/flixel-tools#55]
Mac os 10.10.3

symlink is broken:
'ln -s /Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl ~/bin/subl' [y/n]?
y
ln: /Users/kolombet/bin/subl: No such file or directory

exception:
Uncaught exception - [file_open,/usr/lib/haxelib/flixel-tools/1,1,0/settings.json]

**Comment by Gama11** [comment]
I just pushesd a potential fix for this.

Could you try again after installing the git version of flixel-tools? Just run `haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools`.

Can't test this myself, don't have a mac.

**Comment by anonrab** [comment]
Sorry, i can't test now - my haxelib installation is totally broken. When i run haxelib, it shows me bunch of errors:

haxelib
/usr/lib/haxe/std/neko/_std/Sys.hx:87: characters 2-24 : Error chdir /Users/kolombet/Library/Application
tools/haxelib/Main.hx:309: characters 17-43 : Called from
tools/haxelib/Main.hx:1508: characters 2-22 : Called from
?:1: characters 1048575-8796094070782 : Called from
Aborted

**Comment by Gama11** [comment]
Hm.. You could try downloading and installing the Haxe installer again.

**Comment by Gama11** [comment]
Assuming this is fixed.

**Comment by patrickwijerama** [comment]
Tried it with the git version and it still breaks for me:
Do you want to set up the command alias 'flixel' to 'haxelib run flixel-tools'?
A simple flixel script will be added to your /usr/local/bin/ [y/n]?
y
ln: /usr/local/bin/flixel: File exists

Choose your default IDE:

  [0] Sublime Text
  [1] FlashDevelop
  [2] IntelliJ IDEA
  [3] None

0

Do you want to automatically open the created templates and demos with Sublime Text? [y/n]?
y
For Sublime Text to open automatically you have to make sure the 'subl' command is setup properly on yoursystem as in http://www.sublimetext.com/docs/2/osx_command_line.html.

Do you want to run the symlink command automatically as per official instructionshttp://www.sublimetext.com/docs/2/osx_command_line.html?

 The command that will be executed is as follows:
 'ln -s /Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl ~/bin/subl' [y/n]?
y
Called from ? line 1
Called from FlxTools.hx line 128
Called from FlxTools.hx line 14
Called from a C function
Called from FlxTools.hx line 71
Called from massive/sys/cmd/CommandLineRunner.hx line 109
Called from massive/sys/cmd/CommandLineRunner.hx line 258
Called from commands/SetupCommand.hx line 28
Called from commands/SetupCommand.hx line 209
Called from utils/CommandUtils.hx line 387
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 38
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 54
Uncaught exception - [file_open,/usr/local/lib/haxelib/flixel-tools/git/settings.json]
