### ISSUE TITLE
Tools installation fails on OS X El Capitan

### ISSUE THREAD

**Issue by steverichey** [HaxeFlixel/flixel-tools#59]
Tries to install to `/usr/bin/`, which is now blocked by System Integrity Protection (rootless mode). It should be installed to `/usr/local/`. It also seems that the path to Haxe is hardcoded.

**Comment by brnrdbrk** [comment]
Yeah it looks like its hardcoded. A easy fix for that is now alias flixel="sudo haxelib run flixel-tools". :)

**Comment by steverichey** [comment]
`sudo` doesn't override SIP, so that will not work.

**Comment by jakwings** [comment]
Are you using the latest version of haxe with bug fixes for El Capitan?

**Comment by steverichey** [comment]
Yep, but that's largely irrelevant in this case, as the issue is strictly related to the install path.

**Comment by brnrdbrk** [comment]
Haxelib and flixel-tools installs fine on my 10.11 machine (usr/local). Only problem is that the flixel tool/binary ( that is only a alias for "haxelib run flixel-tools") cannot install because the path seems hard coded.

**Comment by jakwings** [comment]
Oh, sorry. I forgot I just did that myself to place the executable files: https://github.com/HaxeFlixel/flixel-tools/blob/a0adc04ee81fd9d9915da27c6885772f48b52902/src/commands/SetupCommand.hx#L123-L125

Waiting for a patch… seems that `/usr/bin` is hard-coded in quite a few packages.
