### ISSUE TITLE
Setup error under Linux Mint Haxe 3.2.1.

### ISSUE THREAD

**Issue by notalentgeek** [HaxeFlixel/flixel-tools#62]
Hello I want to install HaxeFlixel and this is appear after I run sudo haxelib run flixel-tools setup.
cp: cannot create regular file ‘/usr/lib/haxe/flixel’: No such file or directory
chmod: cannot access ‘/usr/lib/haxe/flixel’: No such file or directory
ln: failed to create symbolic link ‘/usr/bin/flixel’: File exists
What should I do?

**Comment by GimmickyApps** [comment]
Just curious, which version of Mint are you on?  I intended to eventually try my code there too, and I think I'm on a somewhat borked 17.2 install.

Strange you'd get these errors already using sudo.  Not that I've looked at the script directly... I think it would be part of https://github.com/HaxeFlixel/flixel-tools/blob/350f8db46981f3d936f5b3b233e61e325fd2f05e/src/commands/BuildProjectsCommand.hx but I don't understand "haxelib run" scripts very well yet.

**Comment by NoTalentGeek** [comment]
Hello I used Linux Mint 17.3 Cinnamon 64bit. I just try HaXe last December so I am not quite have a grasp.

I used the latest stable release from haxelib install command.

**Comment by seemsindie** [comment]
Hello, i am also having this issue, when i run without sudo i get same as @NoTalentGeek but when i run with sudo i get:

`sudo: unable to stat /etc/sudoers.d/10-installer: Permission denied
sudo: unable to stat /etc/sudoers.d/g_wheel: Permission denied
cp: cannot create regular file '/usr/lib/haxe/flixel': No such file or directory
sudo: unable to stat /etc/sudoers.d/10-installer: Permission denied
sudo: unable to stat /etc/sudoers.d/g_wheel: Permission denied
chmod: cannot access '/usr/lib/haxe/flixel': No such file or directory
sudo: unable to stat /etc/sudoers.d/10-installer: Permission denied
sudo: unable to stat /etc/sudoers.d/g_wheel: Permission denied
ln: failed to create symbolic link '/usr/bin/flixel': File exists
`

And also, you shouldn't run this as sudo, i don't feel secure and good when i do :)

Any idea why is this happening and how to fix it?

**Comment by FryDay** [comment]
This seems to be an issue with Ubuntu 16.04 as well. I believe the line `var haxePath:String = Sys.getEnv("HAXEPATH");` is the issue, as the environment variable HAXEPATH does not seem to be set.

**Comment by madnotdead** [comment]
I'm facing this issue, any workaround?

**Comment by IBwWG** [comment]
That's interesting.  I just tried on Linux Mint 17.2 (32-bit) and it worked fine.  Per the install instructions I'm assuming you all ran `haxelib install flixel-tools` before trying this line...both this and `haxelib run flixel-tools setup` worked flawlessly for me.  The latter seemed to want my sudo password only to create a flixel command in /usr/bin .  Maybe it's a distro difference that yours is trying to put it in /usr/lib/haxe for some reason?  No idea...

**Comment by IBwWG** [comment]
Looks like it's this line in the script: https://github.com/HaxeFlixel/flixel-tools/blob/dev/src/commands/SetupCommand.hx#L120

**Comment by IBwWG** [comment]
Aha, just like @FryDay said, it's the environment variable that's not being set, then...

**Comment by IBwWG** [comment]
So @madnotdead as @FryDay said did you try to install haxe itself via openfl's package, not haxeflixel's?  That might help...

**Comment by IBwWG** [comment]
Also http://www.openfl.org/download/ says to use their zip file instead of a package manager:

> 
If you are a Linux user, we recommend that you do use the above install script instead of your own package manager. The versions of Haxe and Neko distributed on Linux package repositories tend to be old, or experience other issues after the install.

**Comment by madnotdead** [comment]
@IBwWG i'm on Ubuntu 16.04 LTS, i try to install haxe with the install script but got this error:

_install-haxe.sh: 1: install-haxe.sh: Syntax error: Unterminated quoted string_

**Comment by IBwWG** [comment]
Hmm, that seems to be a different issue than the above...I guess if you run 'haxe' it's not installed at all, then?  That might be something for the haxe.org issue tracker, if so.

**Comment by paulorobertocruz** [comment]
@madnotdead 
I thing have a solution, but while i test here there is a workaroud for this.

fist clean link from /usr/bin whith:
sudo unlink /usr/bin/flixel
second copy the script to the /usr/bin:
sudo cp path/to/haxelib/flixel-tools//1\,2\,0/bin/flixel.sh /usr/bin/flixel(careful whith path
third type flixel and see ;)
