### ISSUE TITLE
Add a flixel command to set the correct version of lime+openfl based on the flixel version

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel-tools#69]
Maybe as a part of the flixel setup?

**Comment by Gama11** [comment]
Not sure if that's a good idea.. What does "correct" mean? Sure, right now that's fairly clear, but once we support OpenFL 4, there might be a significant percentage of users who decides to stay on OpenFL 3.6.1 for a while. So then there'd be two different, "equally correct" versions.

**Comment by sruloart** [comment]
Yeah, I get what you mean...but that's really for newcomers who have a hard time figuring out haxelib, so maybe if flixel is not installed it would install and set the minimal version of both libraries to be known to work with that specific version of Flixel?

**Comment by Gama11** [comment]
I mean, installing flixel from haxelib should really already do that, since the dependencies are defined in `haxelib.json`...

**Comment by sruloart** [comment]
but then with each version of openfl/lime you get a different (most likely) non-working set of libraries. This way you can just run flixel setup and get a working set again

**Comment by sruloart** [comment]
Just saw the useful warning when trying to build a project with the "wrong" OpenFL/Lime setup, that's more than enough for new comers :)
