### ISSUE TITLE
Library flixel-tools version 1.4.4 does not have a run script

### ISSUE THREAD

**Issue by jgedri** [HaxeFlixel/flixel-tools#73]
I'm trying to set up flixel-tools on Linux Mint, but apparently there isn't a run script.

**Comment by Gama11** [comment]
That's a lie. :) https://lib.haxe.org/p/flixel-tools/1.4.4/files/run.n

Is that file there in your local copy?

**Comment by Gama11** [comment]
Closing since there's not enough information.
