### ISSUE TITLE
Run lime setup not functioning

### ISSUE THREAD

**Issue by Roselyn393** [HaxeFlixel/flixel-tools#75]
Hello, i am looking to use Haxe to help with a mod I want to work on but to start i need to run a few commands in the command prompt. There is one command that continues to not work properly whenever i use it. The 'haxelib run lime setup flixel' command continues to work but always stops at systools with no reports or acknowledging that it's done so I was wondering if someone could help me fix this 
![problem](https://user-images.githubusercontent.com/103345463/162601679-6eaf97ec-db90-4e58-96a2-2ead2c9ee728.png)

**Comment by Geokureli** [comment]
you could try installing the haxelibs manually

```
haxelib install flixel-addons
haxelib install flixel-ui
haxelib install flixel-demos
haxelib install flixel-tools
haxelib install flixel-templates
```

**Comment by T1mL3arn** [comment]
Got similar `systools` problem - `Error: Could not find dependency "systools" for library "flixel"`. I had old dev flixel as an active version, changed it back to stable release (5.1.0 in my case) and run setup again - no more error, `systools` installed and setup was finished.
